#!/bin/bash
[[ -e ./bits/bootstrap/logging ]] && [[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging
[[ -z "$INFO_LEVEL" ]] && source logging

if [ $1 -ne 0 ] ; then
  error "$ERROR"
  if [ ! -z $2 ] ; then
    error_all $2
  fi
  exit 1
else
  debug_all $2
fi