#!/bin/bash

#-----------
# Install Script
#-----------

echo "Install bootstrap..."
cp ./submodules/bootstrap/files/helloworld /usr/local/bin/helloworld
chmod 755 /usr/local/bin/helloworld
echo "set nocompatible" > /root/.vimrc
echo "DONE Install bootstrap."