#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
set -euo pipefail ; IFS=$'\n\t'

MKDIR_OUTPUT=/tmp/mkdir.log
OWNER=${OWNER-$USER}

while test ${#} -gt 0
do
  VARIABLE=$1

  if [[ -z "${!VARIABLE:-}" ]]; then
    error "Unknown variable $VARIABLE, make sure it is export'ed"
    exit 1
  fi

  DIR=${!VARIABLE}

  if [ ! -e $DIR ] ; then
    SCRIPT_OUTPUT=$(mkdir -p ${DIR} > $MKDIR_OUTPUT 2>&1)
    ERROR="Unable to mkdir -p ${DIR} due to ..." ./submodules/bootstrap/failonerrors $? $MKDIR_OUTPUT
    [ $? -ne 0 ] && exit 1
    debug "  -- Created $VARIABLE ($DIR)"

    if [[ "$USER" != "$OWNER" ]]; then
      SCRIPT_OUTPUT=$(chown -R $OWNER $DIR > $MKDIR_OUTPUT 2>&1)
      ERROR="Unable to chown to $OWNER $DIR due to ..." ./submodules/bootstrap/failonerrors $? $MKDIR_OUTPUT
      [ $? -ne 0 ] && exit 1
      debug "  -- Set ownership to $OWNER ($DIR)"
    fi

  else
    debug "  -- Re-using $VARIABLE ($DIR)"
  fi
  shift
done


