#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging

WGET_PARAMS=${WGET_PARAMS-""}
TARGET_NAME=${TARGET_NAME-$SRC_NAME}
LOCAL_FILE=$SRC_DIR/$TARGET_NAME

if [[ ! -e $LOCAL_FILE ]]; then
  notify "  -- Downloading $NAME from $REMOTE_URL/$SRC_NAME to $LOCAL_FILE"
  (cd $SRC_DIR && wget --quiet $WGET_PARAMS -O $TARGET_NAME $REMOTE_URL/$SRC_NAME)
else
  debug "  -- Already downloaded $NAME to ${LOCAL_FILE}"
fi