#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging

BIT=${1-""}
ARGS=${2-""}

if [[ "$BIT" == "" ]]; then
  notify "Initializing all bits..."
  # todo, use capbash ls to automate this
  capbash bitinit apache
  capbash bitinit cron
  capbash bitinit deploykeys
  capbash bitinit docker
  capbash bitinit drupal
  capbash bitinit elixir
  capbash bitinit git
  capbash bitinit monit
  capbash bitinit mysql
  capbash bitinit nginx
  capbash bitinit phoenix
  capbash bitinit rails
  capbash bitinit tarball
  notify "DONE, Initializing all bits."
elif [[ ! -e "bits/$BIT" ]]; then
  debug "  -- Skipping uninstalled project $BIT"
elif [[ `git remote | grep $BIT` == "$BIT" ]]; then
  debug "  -- Already initialized $BIT"
else
  GIT_OUTPUT=/tmp/bitinit_${BIT}.log
  debug "  -- git remote add $BIT https://github.com/aforward/capbash-$BIT"
  GIT_ERRORS=$(git remote add $BIT https://github.com/aforward/capbash-$BIT > ${GIT_OUTPUT} 2>&1)
  ERROR="Unable to init subtree $BIT from $GIT_URL due to ..." ./bits/bootstrap/failonerrors $? $GIT_OUTPUT
  [ $? -ne 0 ] && exit 1
fi
