#!/bin/bash
BIT=$1

if [[ "$BIT" == "--all" ]]; then
  # todo, use capbash ls to automate this
  capbash install apache
  capbash install cron
  capbash install deploykeys
  capbash install docker
  capbash install drupal
  capbash install elixir
  capbash install git
  capbash install monit
  capbash install mysql
  capbash install nginx
  capbash install phoenix
  capbash install rails
  capbash install tarball
else
  GIT_URL=https://github.com/aforward/capbash-$BIT
  echo "Installing $BIT ($GIT_URL)..."
  git subtree add --prefix=bits/$BIT --squash $GIT_URL master
  BOOTSTRAP_FILE=./bits/$BIT/bootstrap
  if [ -f $BOOTSTRAP_FILE ]; then
    echo "  -- bootstrapping module"
    $BOOTSTRAP_FILE
  fi
  echo "DONE, Installing $BIT ($GIT_URL)."
fi


